appName: appName
logLevel: WARN

Global:
  WEIGHT_PATH: yolo_weights.h5
  MODEL_PATH: ./model.h5

MODEL:
  IMAGE_RESIZE: 224
  FINAL_ACTIVATION: sigmoid
  LOSS_FUNCTION: binary_crossentropy
  LEARNING_RATE: 1e-3 # int
  LOSS_METRICS: [accuracy] # Common accuracy metric for all outputs, but can use different metrics for different output

Training:
  ANNOTATION_PATH: dataset/annotations.txt
  LOGS: logs/training_
  CLASSES: [pedestrian_bb, cyclist_bb, facing_back_bb, on-call_bb, on-mobile_bb]
  ANCHORS: dataset/anchors.txt