appName: appName
logLevel: WARN

Global:
  NUM_CLASSES: 5  # Fixed for our Cats & Dogs classes
  CHANNELS: 3     # Fixed for color images

  IMAGE_RESIZE: 224
  RESNET50_POOLING_AVERAGE: avg
  DENSE_LAYER_ACTIVATION: softmax
  OBJECTIVE_FUNCTION: categorical_crossentropy
  WEIGHT_PATH: ./wegith.h5

# Common accuracy metric for all outputs, but can use different metrics for different output
LOSS_METRICS: [accuracy]

Training:
  NUM_EPOCHS: 10
  EARLY_STOP_PATIENCE: 3 # EARLY_STOP_PATIENCE must be < NUM_EPOCHS

  # These steps value should be proper FACTOR of no.-of-images in train & valid folders respectively
  # Training images processed in each step would be no.-of-train-images / STEPS_PER_EPOCH_TRAINING
  STEPS_PER_EPOCH_TRAINING: 10
  STEPS_PER_EPOCH_VALIDATION: 10

  # These steps value should be proper FACTOR of no.-of-images in train & valid folders respectively
  # NOTE that these BATCH* are for Keras ImageDataGenerator batching to fill epoch step input
  BATCH_SIZE_TRAINING: 100
  BATCH_SIZE_VALIDATION: 100

  # Using 1 to easily manage mapping between test_generator & prediction for submission preparation
  BATCH_SIZE_TESTING: 1